# Generated by Django 3.1.1 on 2020-09-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20200916_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
