# Generated by Django 3.1.1 on 2020-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_destination_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='newspost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='pics')),
                ('post_title', models.CharField(max_length=100)),
                ('post_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.TextField(default='#')),
            ],
        ),
    ]
